os: osx
osx_image: xcode12.2
language: swift
xcode_project: Awesome Counter/Awesome Counter.xcodeproj
xcode_scheme: Awesome Counter
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 11

env:
  global:
    secure: ${{ secrets.SONAR_TOKEN }}

addons:
  sonarcloud:
    organization: "ingjohnguerrero"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}