//
//  WelcomeUserViewController.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class WelcomeUserViewController: UIViewController {

    // MARK: - IBOutlets -

    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var appNameLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var continueButton: UIButton!

    // MARK: - Public properties -

    var presenter: WelcomeUserPresenterInterface!

    // MARK: - Private properties -

    var infoArray: [WelcomeCellType] = [] {
        didSet {
            DispatchQueue.main.async { [weak self] in
                self?.tableView.reloadData()
            }
        }
    }

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        registerTableViewCells()
        loadPresenter()
        presenter.viewDidLoad()
    }

}

// MARK: - Extensions -

extension WelcomeUserViewController: WelcomeUserViewInterface {

    func setTableView(with cellTypeArray: [WelcomeCellType]) {
        infoArray = cellTypeArray
    }

}

extension WelcomeUserViewController {
    func loadPresenter() {
        guard (presenter != nil) else {
            _ = WelcomeUserWireframe.init(moduleViewController: self)
            return
        }
    }
}
