//
//  WelcomeUserPresenter.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class WelcomeUserPresenter {

    // MARK: - Private properties -

    private unowned let view: WelcomeUserViewInterface
    private let wireframe: WelcomeUserWireframeInterface

    // MARK: - Lifecycle -

    init(view: WelcomeUserViewInterface, wireframe: WelcomeUserWireframeInterface) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension WelcomeUserPresenter: WelcomeUserPresenterInterface {
    var cellTypeArray: [WelcomeCellType] {
        return [.almostAnything,.shareable,.countYourThoughs]
    }

    func viewDidLoad() {
        view.setTableView(with: cellTypeArray)
    }

}
