//
//  WelcomeUserInterfaces.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol WelcomeUserWireframeInterface: WireframeInterface {
}

protocol WelcomeUserViewInterface: ViewInterface {
    func setTableView(with cellTypeArray:[WelcomeCellType])
}

protocol WelcomeUserPresenterInterface: PresenterInterface {
    var cellTypeArray: [WelcomeCellType] { get }
    func viewDidLoad()
}
