//
//  WelcomeUserWireframe.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class WelcomeUserWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "WelcomeUser", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: WelcomeUserViewController.self)
        super.init(viewController: moduleViewController)

        let presenter = WelcomeUserPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
    }

    init(moduleViewController: WelcomeUserViewController) {
        super.init(viewController: moduleViewController)
        let presenter = WelcomeUserPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension WelcomeUserWireframe: WelcomeUserWireframeInterface {
}
