//
//  WelcomeUserInterfaces.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

typealias WelcomeUserCellTuple = (color: UIColor, imageName: String, title: String, description: String)

protocol WelcomeUserWireframeInterface: WireframeInterface {
    func goToMainScreen()
}

protocol WelcomeUserViewInterface: ViewInterface {
    func setTableView(with tupleArray:[WelcomeUserCellTuple])
}

protocol WelcomeUserPresenterInterface: PresenterInterface {
    var tupleArray: [WelcomeUserCellTuple] { get }
    func viewDidLoad()
    func goToMainScreen()
}
