# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Awesome Counter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Awesome Counter
  pod 'Alamofire', '~> 5.2'

  target 'Awesome CounterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Awesome CounterUITests' do
    # Pods for testing
  end

end
