//
//  AddItemWireframe.swift
//  Awesome Counter
//
//  Created by John Guerrero on 10/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AddItemWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "AddItem", bundle: nil)

    // MARK: - Module setup -

    init(onAddItemClosure: @escaping (() -> Void)) {
        let moduleViewController = storyboard.instantiateViewController(ofType: AddItemViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = AddItemInteractor()
        let presenter = AddItemPresenter(
            view: moduleViewController,
            interactor: interactor,
            wireframe: self,
            onAddItemClosure: onAddItemClosure
        )
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension AddItemWireframe: AddItemWireframeInterface {
    func goBack() {
        navigationController?.popViewController(animated: true)
    }

    func presentErrorAlert() {
        let alertController: UIAlertController = UIAlertController(
            title: "Couldn’t create the counter",
            message: "The Internet connection appears to be offline.",
            preferredStyle: UIAlertController.Style.alert
        )

        let cancelAction: UIAlertAction = UIAlertAction(
            title: "Dismiss",
            style: UIAlertAction.Style.cancel,
            handler: nil
        )

        alertController.addAction(cancelAction)

        navigationController?.present(alertController, animated: true, completion: nil)
    }
}
