//
//  AddItemPresenter.swift
//  Awesome Counter
//
//  Created by John Guerrero on 10/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AddItemPresenter {

    // MARK: - Private properties -

    private unowned let view: AddItemViewInterface
    private let interactor: AddItemInteractorInterface
    private let wireframe: AddItemWireframeInterface
    private var onAddItemClosure: ((Counter) -> Void)!

    // MARK: - Lifecycle -

    init(view: AddItemViewInterface, interactor: AddItemInteractorInterface, wireframe: AddItemWireframeInterface, onAddItemClosure: @escaping ((Counter) -> Void)) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.onAddItemClosure = onAddItemClosure
    }
}

// MARK: - Extensions -

extension AddItemPresenter: AddItemPresenterInterface {
    func saveCounter(title: String) {
        let counter = Counter(id: "0", title: title, count: 0)
        onAddItemClosure(counter)
    }

}
