//
//  AddItemViewController.swift
//  Awesome Counter
//
//  Created by John Guerrero on 10/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AddItemViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: AddItemPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension AddItemViewController: AddItemViewInterface {
}
