//
//  AddItemViewController.swift
//  Awesome Counter
//
//  Created by John Guerrero on 10/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AddItemViewController: UIViewController {

    // MARK: - IBOutlets -

    @IBOutlet weak var counterTitleLabel: UITextField!
    @IBOutlet weak var saveButton: UIBarButtonItem!

    // MARK: - Public properties -

    var presenter: AddItemPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func goBackButtonTaped(_ sender: Any) {
        navigationController?.popViewController(animated: true)
    }

    @IBAction func onSaveButtonTapped(_ sender: Any) {
        presenter.saveCounter(title: counterTitleLabel.text ?? "")
        navigationController?.popViewController(animated: true)
    }

    @IBAction func onTextFieldChanged(_ sender: UITextField) {
        let counterTitle = sender.text ?? ""
        saveButton.isEnabled = !(counterTitle.isEmpty)
    }

}

// MARK: - Extensions -

extension AddItemViewController: AddItemViewInterface {
}
