//
//  AddItemInterfaces.swift
//  Awesome Counter
//
//  Created by John Guerrero on 10/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AddItemWireframeInterface: WireframeInterface {
}

protocol AddItemViewInterface: ViewInterface {
}

protocol AddItemPresenterInterface: PresenterInterface {
    func saveCounter(title: String)
}

protocol AddItemInteractorInterface: InteractorInterface {
}
