//
//  AddItemInteractor.swift
//  Awesome Counter
//
//  Created by John Guerrero on 10/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AddItemInteractor {
}

// MARK: - Extensions -

extension AddItemInteractor: AddItemInteractorInterface {
}
