//
//  AddItemInteractor.swift
//  Awesome Counter
//
//  Created by John Guerrero on 10/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AddItemInteractor {
    let context = DevelopmentAPIContext(environment: APIEnvironments.production)
    lazy var counterService = AlamofireCounterService(context: context)
}

// MARK: - Extensions -

extension AddItemInteractor: AddItemInteractorInterface {
    func addCounter(title: String, completion: @escaping ([Counter], Error?) -> Void) {
        counterService.createCounter(title: title, completion: completion)
    }
}
