//
//  MainScreenViewController.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainScreenViewController: UIViewController {

    // MARK: - IBOutlets -

    @IBOutlet weak var editButton: UIBarButtonItem!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet var dataProvider: (
                                    UITableViewDataSource &
                                    UITableViewDelegate &
                                    ItemManagerSettable &
                                    SearchableDataProvider
                                )!
    @IBOutlet weak var activityIndicatorView: UIActivityIndicatorView!
    @IBOutlet weak var emptyView: UIView!
    @IBOutlet weak var addButton: UIButton!
    @IBOutlet weak var countersInformationLabel: UILabel!

    // MARK: - Public properties -

    var presenter: MainScreenPresenterInterface!
    var itemManager: CounterItemManager!
    var searchController = UISearchController(searchResultsController: nil)
    lazy var searchBar: UISearchBar! = searchController.searchBar

    // MARK: - Lifecycle -

    fileprivate func setupItemManager() {
        dataProvider.itemManager = itemManager
        dataProvider.itemManager?.onItemAddedClosure = { [weak self] () -> Void in
            self?.setContentView()
        }
    }

    fileprivate func setTableViewDataProvider() {
        tableView.dataSource = dataProvider
        tableView.delegate = dataProvider

        setupItemManager()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        setupNavigationBar()
        registerTableViewCells()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        presenter.viewDidAppear()
    }

    @IBAction func onAddButtonTapped(_ sender: Any) {
        presenter.presentAddItemModule()
    }

    @IBAction func onEmptyViewButtonTapped(_ sender: Any) {
        itemManager.addItem(
            Counter(id: "\(itemManager.itemsCount)",
                    title: "Item \(itemManager.itemsCount)",
                    count: 1)
        )
    }
}

// MARK: - Extensions -

extension MainScreenViewController: MainScreenViewInterface {
    func setContentView() {
        defer {
            updateCounterInformation()
        }
        tableView.reloadData()
        tableView.isHidden = false
        emptyView.isHidden = true
    }

    func startLoading() {
        activityIndicatorView.startAnimating()
        tableView.isHidden = true
        emptyView.isHidden = true
    }

    func finishLoading() {
        activityIndicatorView.stopAnimating()
    }

    func setEmptyView() {
        tableView.isHidden = true
        emptyView.isHidden = false
        countersInformationLabel.text = " ᐧ "
    }

    func setItemManager(_ itemManager: CounterItemManager) {
        self.itemManager = itemManager
        setTableViewDataProvider()
    }

    func updateCounterInformation() {
        countersInformationLabel.text = itemManager.countersInformation
    }
}

extension MainScreenViewController {

    func registerTableViewCells() {
        tableView.register(
            UINib(nibName: "CounterTableViewCell", bundle: nil),
            forCellReuseIdentifier: "CounterTableViewCell"
        )
    }

    func setupNavigationBar() {
        navigationController?.navigationBar.prefersLargeTitles = true
        navigationItem.largeTitleDisplayMode = .automatic
        navigationItem.searchController = searchController

        searchController.searchBar.delegate = self
        searchController.searchBar.tintColor = UIColor(named: "secondaryLabel")
    }
}

extension MainScreenViewController: UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        dataProvider.updateSearchTerm(searchText)
        tableView.reloadData()
    }
}
