//
//  MainScreenInterfaces.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MainScreenNavigationOption {
    case addItem(_ onAddedItemClosure: ((Counter) -> Void))
}

protocol MainScreenWireframeInterface: WireframeInterface {
    func navigate(to option: MainScreenNavigationOption)
}

protocol MainScreenViewInterface: ViewInterface {
    func startLoading()
    func finishLoading()
    func setEmptyView()
    func setContentView()
    func setItemManager(_ itemManager: CounterItemManager)
    func updateCounterInformation()
}

protocol MainScreenPresenterInterface: PresenterInterface {
    func viewDidLoad()
    func viewDidAppear()
    func presentAddItemModule()
}

protocol MainScreenInteractorInterface: InteractorInterface {
}
