//
//  MainScreenPresenter.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MainScreenPresenter {

    // MARK: - Private properties -

    private unowned let view: MainScreenViewInterface
    private let interactor: MainScreenInteractorInterface
    private let wireframe: MainScreenWireframeInterface

    // MARK: - Lifecycle -

    init(view: MainScreenViewInterface, interactor: MainScreenInteractorInterface, wireframe: MainScreenWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MainScreenPresenter: MainScreenPresenterInterface {
    func viewDidLoad() {
        view.startLoading()
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 3.0) {
            self.view.finishLoading()
            self.view.setEmptyView()
        }
    }
}
