//
//  MainScreenWireframe.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainScreenWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "MainScreen", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: MainScreenViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = MainScreenInteractor()
        let presenter = MainScreenPresenter(
            view: moduleViewController,
            interactor: interactor,
            wireframe: self
        )
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MainScreenWireframe: MainScreenWireframeInterface {
    func navigate(to option: MainScreenNavigationOption) {
        switch option {
        case .addItem(let onAddItemClosure):
            presentAddItemModule(onAddItemClosure: onAddItemClosure)
        }
    }

    func presentAddItemModule(onAddItemClosure: @escaping ((Counter) -> Void)) {
        let wireframe = AddItemWireframe(onAddItemClosure: onAddItemClosure)
        navigationController?.pushWireframe(wireframe)
    }

}
