//
//  MainScreenViewController.swift
//  Awesome Counter
//
//  Created by John Guerrero on 2/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainScreenViewController: UIViewController {

    // MARK: - IBOutlets -

    @IBOutlet weak var editButton: UIBarButtonItem!
    @IBOutlet weak var searchBar: UISearchBar!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet var dataProvider: (UITableViewDataSource & UITableViewDelegate & ItemManagerSettable)!
    @IBOutlet weak var activityIndicatorView: UIActivityIndicatorView!
    @IBOutlet weak var emptyView: UIView!
    @IBOutlet weak var addButton: UIButton!
    @IBOutlet weak var countersInformationLabel: UILabel!


    // MARK: - Public properties -

    var presenter: MainScreenPresenterInterface!
    var itemManager: CounterItemManager!

    // MARK: - Lifecycle -

    fileprivate func setupItemManager() {
        dataProvider.itemManager = itemManager
        dataProvider.itemManager?.onItemAddedClosure = { [weak self] () -> Void in
            self?.tableView.reloadData()
            self?.countersInformationLabel.text = self?.itemManager.countersInformation
        }
    }

    fileprivate func setTableViewDataProvider() {
        tableView.dataSource = dataProvider
        tableView.delegate = dataProvider

        setupItemManager()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        registerTableViewCells()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        presenter.viewDidAppear()
    }
    
    @IBAction func onAddButtonTapped(_ sender: Any) {
        itemManager.addItem(Counter(id: "\(itemManager.itemsCount)", title: "Item \(itemManager.itemsCount)", count: 1))
    }
}

// MARK: - Extensions -

extension MainScreenViewController: MainScreenViewInterface {
    func setContentView() {
        defer {
            updateCounterInformation()
        }
        tableView.reloadData()
        tableView.isHidden = false
        emptyView.isHidden = true
    }

    func startLoading() {
        activityIndicatorView.startAnimating()
        tableView.isHidden = true
        emptyView.isHidden = true
    }

    func finishLoading() {
        activityIndicatorView.stopAnimating()
    }

    func setEmptyView() {
        tableView.isHidden = true
        emptyView.isHidden = false
        countersInformationLabel.text = " . "
    }

    func setItemManager(_ itemManager: CounterItemManager) {
        self.itemManager = itemManager
        setTableViewDataProvider()
    }

    func updateCounterInformation() {
        countersInformationLabel.text = itemManager.countersInformation
    }
}

extension MainScreenViewController {

    func registerTableViewCells() {
        tableView.register(UINib(nibName: "CounterTableViewCell", bundle: nil), forCellReuseIdentifier: "CounterTableViewCell")
    }
}
